### ISSUE TITLE
CalendarEditor base plugin/All other editors

### ISSUE THREAD

**Issue by underfisk** [Apollo-Spreadsheet/apollo-spreadsheet#27]
Replace react-datepicker with something similiar that supports 100% styled-components or find out if the component has some kind of styled-components way
This plugin needs to tree-shake all unused code/stylings and that is blocking us of doing it
Also refactor our other inline editors which are not perceptible yet

**Comment by underfisk** [comment]
@VeraRibeiro Could you investigate a plugin that supports this?

**Comment by VeraRibeiro** [comment]
This is the best one that I found since it supports types, style components and it's built in react
However there's no example for this and the runkit isn't working, so I'll have to test to see 
https://www.npmjs.com/package/react-styled-component-calendar

**Comment by underfisk** [comment]
@VeraRibeiro That plugin is very small, does not offer long-term support (last update was 1 year ago) so that's not a viable option. I think our current one is good but if we have in the future to build one from the scratch we'll do.
Another option is to use Material UI calendars, what do you think about that?

**Comment by underfisk** [comment]
We'll be using https://next.material-ui-pickers.dev/demo/datepicker as the official calendar editor
There are a few more editors we should provide by default:
- Dropdown (select in a popper) with search
- Container base for custom editors
