### ISSUE TITLE
Apollo grid custom editor

### ISSUE THREAD

**Issue by VeraRibeiro** [Apollo-Spreadsheet/apollo-spreadsheet#31]
Is your feature request related to a problem? Please describe.
The current editor in apollo grid user Material UI popper, and the size is bigger than the cell
It's also difficult to customize the colour, in main table which is using multiple colours according to the role you can see the colour difference when writing

![image](https://user-images.githubusercontent.com/47228478/113326331-6bf6de00-9311-11eb-808d-3f741fbaa58d.png)

Describe the solution you'd like
We should work on a custom popper which would be the same size as the cells and would take the cells colour

I could work on this if possible

**Comment by underfisk** [comment]
If you could replicate this in a new branch locally, i would like you to create a new storybook example with a clean interface without shadows/elevations/box etc and see if this issue still happens
