### ISSUE TITLE
Element Invalid when passed as string

### ISSUE THREAD

**Issue by VeraRibeiro** [Apollo-Spreadsheet/apollo-spreadsheet#58]
![Screenshot 2021-04-26 at 15 12 12](https://user-images.githubusercontent.com/47228478/116098922-5c19b200-a6a3-11eb-9ba5-61493ea99e58.png)

Code:

![Screenshot 2021-04-26 at 15 26 25](https://user-images.githubusercontent.com/47228478/116099511-f2e66e80-a6a3-11eb-962c-7dd0827478d4.png)

![Screenshot 2021-04-26 at 15 26 37](https://user-images.githubusercontent.com/47228478/116099530-f843b900-a6a3-11eb-97d4-772aa7cf74e9.png)

![Screenshot 2021-04-26 at 15 27 02](https://user-images.githubusercontent.com/47228478/116099535-f974e600-a6a3-11eb-9f49-bb614b6fd82d.png)

**Comment by VeraRibeiro** [comment]
Issue was fixed yesterday in registers, however it's now occurring in Main table allocations

**Comment by underfisk** [comment]
@VeraRibeiro I'll take a look and create some tests to the utility that creates the editor

**Comment by VeraRibeiro** [comment]
This is the error displaying

![Screenshot 2021-04-27 at 12 25 52](https://user-images.githubusercontent.com/47228478/116233828-b6724b80-a753-11eb-8bff-e4269d5f639c.png)

**Comment by underfisk** [comment]
@VeraRibeiro Could you try v1.0.5 ? I have released a hotfix for this issue

**Comment by VeraRibeiro** [comment]
It is now fixed
